### ISSUE TITLE
Different checks for same goal?

### ISSUE THREAD

**Issue by peterjaap** [Memo-ict/vatlayer-sw6#1]
Here the configuration from the extension is used, which apparently is for up to 6.3: https://github.com/Memo-ict/vatlayer-sw6/blob/master/src/Resources/views/storefront/component/address/address-form.html.twig#L18

However, here the configuration from the core is used, which apparently is from 6.4 and up; https://github.com/Memo-ict/vatlayer-sw6/blob/master/src/Resources/views/storefront/component/address/address-personal-vat-id.html.twig#L14

Since the 6.4 check does not work in 6.3, it seems this plugin only works in 6.4. So shouldn't the first check then be replaced with the second check and the configuration option removed?

**Comment by peterjaap** [comment]
It'd be great if there were still a version that would work on 6.3, which would mean removing the 6.4 check and adding the 6.3 check there, which is what I did in my patch;

```
diff --git a/src/Resources/views/storefront/component/address/address-personal-vat-id.html.twig b/src/Resources/views/storefront/component/address/address-personal-vat-id.html.twig
index fd74719..3fd7dca 100644
--- a/src/Resources/views/storefront/component/address/address-personal-vat-id.html.twig
+++ b/src/Resources/views/storefront/component/address/address-personal-vat-id.html.twig
@@ -11,7 +11,7 @@
            data-vatlayer="true"
            data-vatlayer-options="{{ vatlayerOptions | json_encode }}"
            name="vatIds[]"
-        {% if editMode == false and config('core.loginRegistration.vatIdFieldRequired') %}
+        {% if editMode == false and shopware.config.MemoVatlayer6.config.vatIdRequired %}
             required="required"
             data-form-validation-equal="vatIds"
         {% endif %}

```

**Comment by MemoICT** [comment]
@peterjaap we solved this in the 1.0.1 version.

**Comment by peterjaap** [comment]
@MemoICT it looks like you just added `shopware.` before `config`, but that doesn't solve this specific issue? It does two separate checks, why?

**Comment by MemoICT** [comment]
@peterjaap do you mean why this check is in 2 template files ? 

In shopware 6.3.5 they changed the location of the vat check from address to personal and added the core configuration for mandatory field. Prior to this we use a config option in the plugin to set this to mandatory. In the config there is a hint that the option will not work anymore and it can be set through the shopware config.
![image](https://user-images.githubusercontent.com/35326827/125959458-2e0a615f-8612-45f1-841d-142ce20f7570.png)
